### ISSUE TITLE
ready to use?

### ISSUE THREAD

**Issue by gasacchi** [instantOS/instantOS#58]
Hi, i using manjaro i3 in my daily base, so when i saw instant os, i suddenly want to replace my current manjaro with this distro and i love instantwm. but still l have question, is it stable enough for daily use? thanks

**Comment by con-f-use** [comment]
It's in beta. Currently a few key features are missing, such as a good mechanism to change the keyboard shortcuts, see the [roadmap](https://github.com/instantOS/instantOS/projects/1). Things are changing quiet rapidly, but we did not have a major breakage, at least since I've come on. So, you decide! If you want to be absolutely sure, you wait for an 1.0 release.

Btw., can I ask you to ask such questions on Discord or one of the other [community outlets](https://instantos.io/support)? It does not really merit an issue on source hosting.
