### ISSUE TITLE
Source Programs

### ISSUE THREAD

**Issue by noamzaks** [instantOS/instantOS#78]
**Is your feature request related to a problem? Please describe.**
I wanted to change the cursor style from block to I-Beam in the terminal, and I couldn't find the st source code in order to change the config and recompile.

**Describe the solution you'd like**
Perhaps the source code (st-instantos) for ST and other programs compiled from source could be made available in $HOME/.local/src, /usr/local/src or some other directory?

**Additional context**
Just a sidenote: I really like the OS!

**Comment by con-f-use** [comment]
The source for st-instantos can be found here: https://github.com/instantOS/st-instantos
You are welcome do download it and make your modifications.

I see no point in including the sources with the distribution. It would just be overhead for most people, who will never change them. There is also the problem of what to do with user customizations when an update is released. Additionally, people can change the default terminal to anything they like, in the top right corner settings menu, which is the cleaner option if you want to customize the terminal as opposed to overwriting (and possible bricking) the one instantOS ships with.

**Comment by paperbenni** [comment]
The reason why I don't include the sources with the distro is source control. If people know how to use git they can clone from GitHub. If not then they shouldn't modify the source, at least in this state. 
Working without source control discourages updates and being in beta you would irreversibly base your work off something incomplete and potentially unstable. Providing support for modified builds is a lot harder, if people are working without source control as any bug could be the result of their changes. And even if their fork is public, me spending time improving features/changes that only one person uses instead of making the OS better for everyone is not a good trade off. 
Lastly, modifying the source code is not exactly user friendly. If you can program it's an inconvenience, if you're not and coming from windows/ubuntu then it's straight up a wall blocking you out. The goal with instantOS is runtime configuration and to make these power user features accessible to non-techies/beginners as well.
